services:
  front:
    build: ./front
    ports:
      - "8080:3435"
    depends_on:
      - "back"
  back:
    build: ./back-nest
    ports:
      - "3000:8080"
    depends_on:
      - "db"
  db:
    image: postgres:alpine3.14
    ports:
      - "8080:${POSTGRES_PORT}"