services:
  front:
    build: ./front
    ports:
      - "8080:8080"
    depends_on:
      - "back"
  back:
    build: ./back-nest
    ports:
      - "3000:3000"
    depends_on:
      - "db"
  db:
    image: postgres:alpine3.14