services:
  front:
    build: ./front
    ports:
      - "3435:80"
  back:
    build: ./back-nest
    ports:
      - "8080:3000"
    depends_on:
      - "db"
  db:
    container_name: kayo_db
    image: postgres:alpine3.14
    environment:
    - POSTGRES_USER=${POSTGRES_USER}
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    - POSTGRES_DB=${POSTGRES_NAME}
    ports:
      - "${POSTGRES_PORT}:5432"
