apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector:
      matchLabels:
        app: postgres
  template:
    metadata:
      name: postgres
      labels: 
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:12
        ports:
          - containerPort: 5432
            hostPort: 5432
        volumeMounts:
          - mountPath: "/var/lib/postgresql/data"
            name: postgres-volume-claim
        envFrom:
        - configMapRef:
            name: configmap-postgres
        - secretRef:
            name: secret-postgres
      volumes:
        - name: postgres-volume-claim
          persistentVolumeClaim:
            claimName: volume-claim-postgres
      restartPolicy: Always